### ISSUE TITLE
Build fails with lucene6

### ISSUE THREAD

**Issue by bwzhou** [mikemccand/luceneserver#2]
This does not compile. I ran 'build.py package' and got 2108 errors from javac, such as:

`ERROR: command "javac -Xmaxerrs 10000 -d build/classes/java -cp lib/jackson-core
-2.8.2.jar:lib/commons-codec-1.10.jar:lib/json-smart-1.2.jar:lucene6x/lucene/bui
ld/core/lucene-core-6.3.0-SNAPSHOT.jar:lucene6x/lucene/build/analysis/common/luc
ene-analyzers-common-6.3.0-SNAPS..." failed:
src/java/org/apache/lucene/server/SearchQueue.java:27: error: package org.apache
.lucene.util does not exist
import org.apache.lucene.util.StringHelper;
                             ^
src/java/org/apache/lucene/server/QueryID.java:22: error: package org.apache.luc
ene.util does not exist
import org.apache.lucene.util.StringHelper;
                             ^
src/java/org/apache/lucene/server/GlobalState.java:54: error: package org.apache
.lucene.facet.taxonomy.SearcherTaxonomyManager does not exist
import org.apache.lucene.facet.taxonomy.SearcherTaxonomyManager.SearcherAndTaxon
omy;
                                                               ^
src/java/org/apache/lucene/server/GlobalState.java:55: error: package org.apache
.lucene.index does not exist
import org.apache.lucene.index.Term;
                              ^
`

**Comment by mikemccand** [comment]
Hmm no good!  Indeed, I can reproduce this with a fresh clone.  I'll dig ...

**Comment by mikemccand** [comment]
OK I pushed a fix: the Lucene version needed to be bumped to `6.4.0-SNAPSHOT` ... I'll think about how to do this more cleanly going forward.  I think I should check out a specific commit hash from Lucene's 6.x branch instead, and upgrade that periodically/explicitly.

Can you try again?  I was able to make a fresh clone and run `./build.py package`, producing this output:

```
mike@skylake:/l$ /l/testing [master|✔] 
06:27 $ ./build.py package
init: create ./lib directory...
Download http://central.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.8.2/jackson-core-2.8.2.jar -> lib/jackson-core-2.8.2.jar...
  done: 274.4 KB
Download http://central.maven.org/maven2/commons-codec/commons-codec/1.10/commons-codec-1.10.jar -> lib/commons-codec-1.10.jar...
  done: 277.5 KB
Download http://central.maven.org/maven2/net/minidev/json-smart/1.2/json-smart-1.2.jar -> lib/json-smart-1.2.jar...
  done: 52.9 KB
init: cloning lucene branch_6x to ./lucene6x...
build lucene core JAR...
build lucene analyzers-common JAR...
build lucene analyzers-icu JAR...
build lucene facet JAR...
build lucene codecs JAR...
build lucene grouping JAR...
build lucene highlighter JAR...
build lucene misc JAR...
build lucene suggest JAR...
build lucene replicator JAR...
compile 92 sources
build build/luceneserver-0.1.1-SNAPSHOT.jar

Wrote build/luceneserver-0.1.1-SNAPSHOT.zip (20.5 MB)
```

**Comment by bwzhou** [comment]
It builds now. Thanks for the quick response!

**Comment by mikemccand** [comment]
Yay, thanks for testing!
